Refactor CI workflow for kernel build process

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,58 +1,273 @@
-name: GKI Kernel Module Build
-
+name: Buildkernel
 on:
   workflow_dispatch:
+    inputs:
+      Android_Release:
+        description: "Kernel Android Release"
+        required: true
+        type: choice
+        default: '15'
+        options:
+           - '14'
+           - '15'
+      Kernel_Version:
+        description: "Kernel Version"
+        required: true
+        type: choice
+        default: '6.6'
+        options:
+           - '6.1'
+           - '6.6'
+      Security_Patch:
+        description: "(Recommend same as stock kernel)  ㅤㅤㅤKernel Security Patch or lts (latest)"
+        required: true
+        default: '2025-09'
+      Kernel_Suffix:
+        description: "(Recommend same as stock kernel)ㅤ‏‎‏‎‏‎‏‎ ㅤ‏‎‏‎‏‎‏‎ ㅤ‏‎‏‎‏‎‏‎ ㅤ‏‎‏‎‏‎‏‎ (Just delete the dirty suffix,fill in [no]) Kernel Suffix"
+        required: false
+        default: 'g4b48560cd07d-ab14239520-4k'
+      Kernel_Time:
+        description: "(Recommend same as stock kernel)  ㅤㅤㅤKernel Build Timestamp"
+        required: true
+        default: 'Thu Oct  9 05:51:31 UTC 2025'
+      Enable_KPM_Feature:
+        description: "Enable KPM Feature"
+        required: false
+        default: false
+        type: boolean
 
 jobs:
-  build:
-    name: GKI Kernel Module Build
-    runs-on: ubuntu-22.04
-    needs: upload-artifact
-    strategy:
-      matrix:
-        tag:
-          - android12-5.10
-          - android13-5.10
-          - android13-5.15
-          - android14-5.15
-          - android14-6.1
-          - android15-6.6
-          - android16-6.12
-        arch:
-          - aarch64
-          - x86_64
+  Details:
+    runs-on: ubuntu-latest
+    env:
+      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
+      CCACHE_NOHASHDIR: "true"
+      CCACHE_HARDLINK: "true"
 
     steps:
       - name: Maximize build space
-        uses: easimon/maximize-build-space@master
+        uses: AdityaGarg8/remove-unwanted-software@v5
         with:
-          root-reserve-mb: 8192
-          temp-reserve-mb: 2048
           remove-dotnet: 'true'
-          remove-android: 'true'
-          remove-haskell: 'true'
-          remove-codeql: 'true'
+          
+      - name: Set up repo
+        run: |
+         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
+         chmod a+x ~/repo
+         sudo mv ~/repo /usr/local/bin/repo
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+      - name: Sync GKI source code
+        run: |
+         mkdir Buildkernel
+         cd Buildkernel
+         git config --global user.email "usererror404@gmail.com"
+         git config --global user.name "usererror404"
+         repo init -u https://android.googlesource.com/kernel/manifest -b common-android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}-${{ github.event.inputs.Security_Patch }} --depth=1
+         repo sync
 
-      - name: Run GKI Kernel Build Action
-        uses: ./
+      - name: Fix 6.6 Build
+        if: ${{ github.event.inputs.Kernel_Version == '6.6' }}
+        run: |
+          cd Buildkernel/common
+          FORMATTED_BRANCH="android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}"
+          # Fake Patch to fix failures
+          fake_patched=0
+          if [ "$FORMATTED_BRANCH" = "android15-6.6" ]; then
+            if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
+              echo "Can't find nr_subpages try to repair"
+              sed -i -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' ./fs/proc/task_mmu.c
+              fake_patched=1
+            fi
+          fi
+
+          if [ "$fake_patched" = 1 ]; then
+            if [ "$FORMATTED_BRANCH" = "android15-6.6" ]; then
+              if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
+                sed -i -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' -e '/pagemap_entry_t \*res = NULL;/d' ./fs/proc/task_mmu.c
+              fi
+            fi
+          fi
+
+      - name: Set up SukiSU-Ultra
+        run: |
+         cd Buildkernel
+         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s builtin
+        
+      - name: Set up susfs
+        run: |
+         cd Buildkernel
+         git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}
+         cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}.patch ./common/
+         cp susfs4ksu/kernel_patches/fs/* ./common/fs/
+         cp susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+         cd common
+         patch -p1 -F 3 < 50_add_susfs_in_gki-android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}.patch
+           
+      - name: Add configuration to kernel
+        run: |
+         cd Buildkernel
+         
+         # Define all extra configs
+         EXTRA_CONFIGS=(
+           # User Custom configs
+           CONFIG_SYSCTL
+           CONFIG_SYSVIPC
+           CONFIG_POSIX_MQUEUE
+           CONFIG_NAMESPACES
+           CONFIG_PID_NS
+           CONFIG_UTS_NS
+           CONFIG_IPC_NS
+           CONFIG_USER_NS
+           CONFIG_SECCOMP
+           CONFIG_SECCOMP_FILTER
+           CONFIG_CGROUPS
+           CONFIG_CGROUP_DEVICE
+           CONFIG_CGROUP_PIDS
+           CONFIG_MEMCG
+           CONFIG_DEVTMPFS
+           CONFIG_OVERLAY_FS
+           CONFIG_FW_LOADER
+           CONFIG_FW_LOADER_USER_HELPER
+           CONFIG_FW_LOADER_COMPRESS
+           CONFIG_NET_NS
+           CONFIG_VETH
+           CONFIG_BRIDGE
+           CONFIG_NETFILTER
+           CONFIG_NETFILTER_ADVANCED
+           CONFIG_NF_CONNTRACK
+           CONFIG_IP_NF_IPTABLES
+           CONFIG_IP_NF_FILTER
+           CONFIG_NF_NAT
+           CONFIG_IP_NF_TARGET_MASQUERADE
+           CONFIG_NETFILTER_XT_TARGET_MASQUERADE
+           CONFIG_NETFILTER_XT_TARGET_TCPMSS
+           CONFIG_IP_ADVANCED_ROUTER
+           CONFIG_IP_MULTIPLE_TABLES
+           
+           # susfs configs
+           CONFIG_KSU
+           CONFIG_KSU_SUSFS
+           CONFIG_KSU_SUSFS_SUS_MAP
+           CONFIG_KSU_SUSFS_SUS_PATH
+           CONFIG_KSU_SUSFS_SUS_MOUNT
+           CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT
+           CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT
+           CONFIG_KSU_SUSFS_SUS_KSTAT
+           CONFIG_KSU_SUSFS_TRY_UMOUNT
+           CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT
+           CONFIG_KSU_SUSFS_SPOOF_UNAME
+           CONFIG_KSU_SUSFS_ENABLE_LOG
+           CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS
+           CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG
+           CONFIG_KSU_SUSFS_OPEN_REDIRECT
+           
+           # tmpfs configs
+           CONFIG_TMPFS_XATTR
+           CONFIG_TMPFS_POSIX_ACL
+         )
+         
+         DEFCONFIG_PATH="./common/arch/arm64/configs/gki_defconfig"
+         
+         # Loop through configs to safely add them without duplicates
+         for config in "${EXTRA_CONFIGS[@]}"; do
+           # Remove existing active entry
+           sed -i "/^${config}=/d" "$DEFCONFIG_PATH"
+           # Remove existing inactive entry
+           sed -i "/^# ${config} is not set/d" "$DEFCONFIG_PATH"
+           # Append as active
+           echo "${config}=y" >> "$DEFCONFIG_PATH"
+         done
+         
+         sed -i 's/check_defconfig//' ./common/build.config.gki
+         echo -e "\e[33m[Done]\e[0m" Add configuration to kernel
+      
+      - name: Add KPM configuration to kernel
+        if: ${{inputs.Enable_KPM_Feature }}
+        run: |
+         cd Buildkernel
+         echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo -e "\e[33m[Done]\e[0m" Add KPM configuration to kernel
+         echo -e "\e[33m[Done]\e[0m" Enable KPM feature
+
+      - name: Set up kernel suffix
+        run: |
+         cd Buildkernel
+         if [ "${{ github.event.inputs.Kernel_Version }}" = "6.1" ] &&  [ "${{ github.event.inputs.Kernel_Suffix }}" = "no" ]; then
+          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
+          echo -e "\e[33m[Done]\e[0m" Delete the dirty suffix
+         fi
+         if [ "${{ github.event.inputs.Kernel_Version }}" = "6.6" ] &&  [ "${{ github.event.inputs.Kernel_Suffix }}" = "no" ]; then
+          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
+          sed -i '/^CONFIG_LOCALVERSION=/ s/="\([^"]*\)"/=""/' ./common/arch/arm64/configs/gki_defconfig
+          echo -e "\e[33m[Done]\e[0m" Delete the dirty suffix
+         fi         
+         if [ "${{ github.event.inputs.Kernel_Version }}" = "6.1" ] && [ "${{ github.event.inputs.Kernel_Suffix }}" != "no" ]; then
+          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
+          sed -i '$s|echo "\$res"|echo "$res-${{ github.event.inputs.Kernel_Suffix }}"|' ./common/scripts/setlocalversion
+          echo -e "\e[33m[Done]\e[0m" Set up custom suffix
+         fi
+         if [ "${{ github.event.inputs.Kernel_Version }}" = "6.6" ] && [ "${{ github.event.inputs.Kernel_Suffix }}" != "no" ]; then
+          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
+          sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" ./common/scripts/setlocalversion
+          sudo sed -i "s/-4k/-${{ github.event.inputs.Kernel_Suffix }}/g" ./common/arch/arm64/configs/gki_defconfig
+          echo -e "\e[33m[Done]\e[0m" Set up custom suffix
+         fi
+
+      - name: Set up kernel build timestamp
+        run: |
+         cd Buildkernel
+         perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT ${{ github.event.inputs.Kernel_Time }}\"}" ./common/scripts/mkcompile_h
+         sed -i -e "s|\$(preempt-flag-y) \"\$(build-timestamp)\"|\$(preempt-flag-y) \"${{ github.event.inputs.Kernel_Time }}\"|" ./common/init/Makefile
+         echo -e "\e[33m[Done]\e[0m" Set up kernel build timestamp
+
+      - name: Build kernel
+        run: |
+         cd Buildkernel
+         sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
+         rm -rf ./common/android/abi_gki_protected_exports_*
+         sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' common/build.config.gki.aarch64
+         sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' common/build.config.gki.aarch64
+         sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' common/build.config.gki.aarch64
+         tools/bazel run --config=fast --lto=thin //common:kernel_aarch64_dist -- --destdir=dist
+         
+      - name: KPM patch
+        if: ${{inputs.Enable_KPM_Feature }}
+        run: |
+         cd Buildkernel/dist
+         curl -LO "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux"
+         chmod 777 patch_linux
+         ./patch_linux
+         rm Image
+         mv oImage Image
+         echo -e "\e[33m[Done]\e[0m" KPM feature is enabled
+         
+      - name: Output kernel
+        run: |
+         cd Buildkernel/dist
+         cp Image kernel
+
+      - name: Set up AnyKernel3
+        run: |
+         cd Buildkernel
+         git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git
+
+      - name: Create AnyKernel3
+        run: |
+         cd Buildkernel/SukiSU_patch/AnyKernel3
+         cp ../../dist/Image ./
+         zip -r "android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}-AnyKernel3.zip" ./*
+
+      - name: Output AnyKernel3
+        run: |
+         cd Buildkernel
+         mkdir -p patched
+         cp dist/kernel patched/
+         cp SukiSU_patch/AnyKernel3/android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}-AnyKernel3.zip patched/
+
+      - name: Upload Kernel and AnyKernel3
+        uses: actions/upload-artifact@v5
         with:
-          arch: ${{ matrix.arch }}
-          tag: ${{ matrix.tag }}
-          module-name: hello-ko
-          module-path: hello-ko
-
-  upload-artifact:
-    name: Upload LKM Source Code
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Upload LKM Source Code
-        uses: actions/upload-artifact@v4
-        with:
-          name: hello-ko
-          path: .github/hello-ko
+          name: Kernel_AnyKernel3-android${{ github.event.inputs.Android_Release }}-${{ github.event.inputs.Kernel_Version }}
+          path: |
+            Buildkernel/patched/kernel
+            Buildkernel/patched/*.zip
